### PR TITLE
made a table structure for shorturl

### PR DESCRIPTION
**Pull request by anubhav823**

### CODE REVIEW

**Comment by anubhav823** [comment]
Hi @hakxcore 
I have raised a PR for creating a table structure for shorturl.
Please let me know if it is okay

**Review by ghost — APPROVED** [review]
Thankyou for thinking of to contribute to the project
Appriciated your contribution 🎉
Along: One or two of the url shortening services aren't in the working condition i would like to suggest you if you can find and implement new shortening services in the code-snippet

PS: Please reply me if you would like to contribute😇
#happyhacktoberfest

**Comment by hakxcore** [comment]
Thankyou for your contribution 🎉

**Comment by anubhav823** [comment]
Hi,
Yes, I will try to work on it.
However, I am new to bash scripting. Can you point me to where I should look for the error?

**Comment by anubhav823** [comment]
@hakxcore it seems the sites https://ttm.sh and https://0x0.st are not shortening urls anymore. Can you please check if I am correct?

**Comment by hakxcore** [comment]
Yes you are right
Also with that, if we can find open-source URL shorteners then it would be more efficient.

I'm thinking of bitly.com but it's also paid
Btw whatever you think is good to be implemented that also would be great as of now.

**Pull request merged**
